# Generated by Django 5.0.6 on 2024-06-04 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_remove_category_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='description_model',
        ),
    ]
