# Generated by Django 5.0.6 on 2024-06-07 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_paymentgatewaysettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentgatewaysettings',
            options={'verbose_name': 'PaymentGatewaySetting', 'verbose_name_plural': 'PaymentGatewaySettings'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address_line2',
        ),
        migrations.AddField(
            model_name='order',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_note',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_paid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='paymentgatewaysettings',
            table='paymentgatewaysettings',
        ),
    ]
